animations {
    enabled = yes

    bezier = easeOutExpo,   0.16, 1,    0.3,  1
    bezier = easeInOutCubic,0.65, 0.05, 0.36, 1
    bezier = linear,        0,    0,    1,    1
    bezier = almostLinear,  0.5,  0.5,  0.75, 1
    bezier = quick,         0.15, 0,    0.1,  1
    bezier = spring,        0.22, 1,    0.36, 1

    animation = global,        1, 8,  default
    animation = border,        1, 5,  easeOutExpo
    animation = borderangle,   1, 8,  linear, loop

    animation = windows,       1, 5,  spring
    animation = windowsIn,     1, 4,  easeOutExpo, popin 80%
    animation = windowsOut,    1, 3,  easeInOutCubic, popin 80%
    animation = windowsMove,   1, 4,  spring

    animation = fadeIn,        1, 3,  almostLinear
    animation = fadeOut,       1, 2,  almostLinear
    animation = fade,          1, 4,  quick

    animation = layers,        1, 4,  spring
    animation = layersIn,      1, 4,  easeOutExpo, fade
    animation = layersOut,     1, 2,  linear,      fade
    animation = fadeLayersIn,  1, 2,  almostLinear
    animation = fadeLayersOut, 1, 2,  almostLinear

    animation = workspaces,    1, 4,  spring,      slide
    animation = workspacesIn,  1, 4,  spring,      slide
    animation = workspacesOut, 1, 3,  easeInOutCubic, slide
    animation = specialWorkspace, 1, 4, spring,    slidevert
}
