decoration {
    rounding = 10
    rounding_power = 2

    active_opacity   = 0.95
    inactive_opacity = 0.85

    shadow {
        enabled      = true
        range        = 20
        render_power = 3
        color        = rgba(18192600)
        color_inactive = rgba(18192600)
    }

    blur {
        enabled          = true
        size             = 8
        passes           = 3
        noise            = 0.05
        contrast         = 0.9
        brightness       = 0.8
        xray             = false
        new_optimizations = true
        ignore_opacity   = true
        popups           = true
    }
}

# Layer rules for blur on bars/shells
layerrule = blur, noctalia
layerrule = blur, gtk-layer-shell
layerrule = ignorezero, noctalia
layerrule = ignorezero, gtk-layer-shell
